### ISSUE TITLE
the code doesn't work with tf1.3

### ISSUE THREAD

**Issue by gustavkk** [marian-margeta/gait-recognition#1]
hi,@marian-margeta. Thanks for your sharing.
I run dummy_pose_estimation.py, then encountered such a error
////////////////////////////////////////////
runfile('E:/Projects/Tensorflow/gait-recognition/dummy_pose_estimation.py', wdir='E:/Projects/Tensorflow/gait-recognition')
C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\matplotlib\__init__.py:1405: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
Traceback (most recent call last):

  File "<ipython-input-1-f189efdd24b3>", line 1, in <module>
    runfile('E:/Projects/Tensorflow/gait-recognition/dummy_pose_estimation.py', wdir='E:/Projects/Tensorflow/gait-recognition')

  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\spyder\utils\site\sitecustomize.py", line 688, in runfile
    execfile(filename, namespace)

  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "E:/Projects/Tensorflow/gait-recognition/dummy_pose_estimation.py", line 9, in <module>
    net_pose = HumanPoseIRNetwork()

  File "E:\Projects\Tensorflow\gait-recognition\human_pose_nn.py", line 399, in __init__
    super().__init__(log_name, self.HEATMAP_SIZE, self.IMAGE_SIZE, loss_type, is_training)

  File "E:\Projects\Tensorflow\gait-recognition\human_pose_nn.py", line 68, in __init__
    self.network, self.feature_tensor = self.get_network(self.network, is_training)

  File "E:\Projects\Tensorflow\gait-recognition\human_pose_nn.py", line 407, in get_network
    net, end_points = inception_resnet_v2(input_tensor, is_training = is_training)

  File "E:\Projects\Tensorflow\gait-recognition\inception_resnet_v2.py", line 169, in inception_resnet_v2
    tower_conv2_2, tower_pool_1])

  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1061, in concat
    dtype=dtypes.int32).get_shape(

  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 611, in convert_to_tensor
    as_ref=False)

  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 676, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)

  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\constant_op.py", line 121, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)

  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))

  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 376, in make_tensor_proto
    _AssertCompatible(values, dtype)

  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))

TypeError: Expected int32, got list containing Tensors of type '_Message' instead.
/////////////////////////////////////////////
my python environment was set as follows
////////////////
alabaster                 0.7.10                   py35_0    conda-forge
asn1crypto                0.22.0                   py35_0    conda-forge
astroid                   1.5.3                    py35_0    conda-forge
babel                     2.4.0                    py35_0    conda-forge
bleach                    1.5.0                    py35_0    conda-forge
ca-certificates           2017.7.27.1                   0    conda-forge
certifi                   2017.7.27.1              py35_0    conda-forge
cffi                      1.10.0                   py35_0    conda-forge
chardet                   3.0.4                    py35_0    conda-forge
colorama                  0.3.9                    py35_0    conda-forge
cryptography              1.9                      py35_0    conda-forge
cycler                    0.10.0                   py35_0    conda-forge
decorator                 4.1.2                    py35_0    conda-forge
docutils                  0.14                     py35_0    conda-forge
entrypoints               0.2.3                    py35_1    conda-forge
freetype                  2.7                      vc14_1  [vc14]  conda-forge
h5py                      2.7.0               np111py35_1    conda-forge
hdf5                      1.8.18                   vc14_1  [vc14]  conda-forge
html5lib                  0.9999999                py35_0    conda-forge
icu                       58.1                     vc14_1  [vc14]  conda-forge
idna                      2.5                      py35_0    conda-forge
imagesize                 0.7.1                    py35_0    conda-forge
ipykernel                 4.6.1                    py35_0    conda-forge
ipython                   6.1.0                    py35_0    conda-forge
ipython_genutils          0.2.0                    py35_0    conda-forge
isort                     4.2.9                    py35_0    conda-forge
jedi                      0.10.2                   py35_0    conda-forge
jinja2                    2.9.6                    py35_0    conda-forge
jpeg                      9b                       vc14_0  [vc14]  conda-forge
jsonschema                2.5.1                    py35_0    conda-forge
jupyter_client            5.1.0                    py35_0    conda-forge
jupyter_core              4.3.0                    py35_0    conda-forge
keras                     2.0.6                    py35_0    conda-forge
lazy-object-proxy         1.3.1                    py35_0    conda-forge
libgpuarray               0.6.9                    vc14_0  [vc14]  conda-forge
libpng                    1.6.28                   vc14_0  [vc14]  conda-forge
libtiff                   4.0.6                    vc14_7  [vc14]  conda-forge
mako                      1.0.7                    py35_0    conda-forge
Markdown                  2.6.9                     <pip>
markupsafe                1.0                      py35_0    conda-forge
matplotlib                2.0.2                    py35_2    conda-forge
mccabe                    0.6.1                    py35_0    conda-forge
mistune                   0.7.4                    py35_0    conda-forge
mkl                       2017.0.3                      0
nbconvert                 5.2.1                    py35_1    conda-forge
nbformat                  4.3.0                    py35_0    conda-forge
numpy                     1.11.3                   py35_0
numpy                     1.13.1                    <pip>
numpydoc                  0.7.0                    py35_0    conda-forge
olefile                   0.44                     py35_0    conda-forge
opencv3                   3.1.0                    py35_0    menpo
openssl                   1.0.2l                   vc14_0  [vc14]  conda-forge
pandoc                    1.19.2                        0    conda-forge
pandocfilters             1.4.1                    py35_0    conda-forge
pickleshare               0.7.4                    py35_0    conda-forge
pillow                    4.2.1                    py35_1    conda-forge
pip                       9.0.1                    py35_0    conda-forge
prompt_toolkit            1.0.15                   py35_0    conda-forge
protobuf                  3.4.0                     <pip>
psutil                    5.2.2                    py35_0    conda-forge
pycodestyle               2.3.1                    py35_0    conda-forge
pycparser                 2.18                     py35_0    conda-forge
pyflakes                  1.6.0                    py35_0    conda-forge
pygments                  2.2.0                    py35_0    conda-forge
pygpu                     0.6.9               np111py35_0    conda-forge
pylint                    1.7.1                    py35_0    conda-forge
pyopenssl                 17.2.0                   py35_0    conda-forge
pyparsing                 2.2.0                    py35_0    conda-forge
pyqt                      5.6.0                    py35_4    conda-forge
pysocks                   1.6.7                    py35_0    conda-forge
python                    3.5.3                         3    conda-forge
python-dateutil           2.6.1                    py35_0    conda-forge
pytz                      2017.2                   py35_0    conda-forge
PyYAML                    3.12                      <pip>
pyyaml                    3.12                     py35_1    conda-forge
pyzmq                     16.0.2                   py35_2    conda-forge
qt                        5.6.2                    vc14_1  [vc14]  conda-forge
qtawesome                 0.4.4                    py35_0    conda-forge
qtconsole                 4.3.1                    py35_0    conda-forge
qtpy                      1.3.1                    py35_0    conda-forge
requests                  2.18.4                   py35_1    conda-forge
rope                      0.10.5                   py35_0    conda-forge
scipy                     0.19.0              np111py35_0
setuptools                36.2.2                   py35_0    conda-forge
setuptools                36.3.0                    <pip>
simplegeneric             0.8.1                    py35_0    conda-forge
sip                       4.18                     py35_1    conda-forge
six                       1.10.0                    <pip>
six                       1.10.0                   py35_1    conda-forge
snowballstemmer           1.2.1                    py35_0    conda-forge
sphinx                    1.6.3                    py35_0    conda-forge
sphinxcontrib-websupport  1.0.1                    py35_0    conda-forge
spyder                    3.2.1                    py35_0    conda-forge
tensorflow-gpu            1.3.0                     <pip>
tensorflow-tensorboard    0.1.5                     <pip>
testpath                  0.3.1                    py35_0    conda-forge
theano                    0.9.0                    py35_2    conda-forge
tk                        8.5.19                   vc14_1  [vc14]  conda-forge
tornado                   4.5.1                    py35_0    conda-forge
traitlets                 4.3.2                    py35_0    conda-forge
typing                    3.6.2                    py35_0    conda-forge
urllib3                   1.22                     py35_0    conda-forge
vc                        14                            0    conda-forge
vs2015_runtime            14.0.25420                    0    conda-forge
wcwidth                   0.1.7                    py35_0    conda-forge
webencodings              0.5                      py35_0    conda-forge
Werkzeug                  0.12.2                    <pip>
wheel                     0.29.0                   py35_0    conda-forge
wheel                     0.29.0                    <pip>
win_inet_pton             1.0.1                    py35_1    conda-forge
win_unicode_console       0.5                      py35_0    conda-forge
wincertstore              0.2                      py35_0    conda-forge
wrapt                     1.10.11                  py35_0    conda-forge
yaml                      0.1.6                    vc14_0  [vc14]  conda-forge
zlib                      1.2.8                    vc14_3  [vc14]  conda-forge
//////////////////////////////////////
It is written that tensorflow1.0 is used in ReadMe.
I used tf1.3 which is installed using pip. Could you tell me how to overcome this problem?
Thanks in advance.

**Comment by marian-margeta** [comment]
Hi @gustavkk ,
thank you for reporting. In Tensorflow 1.3 there was changed some names of functions and order of their parameters. I have fixed it so now it should be compatible with Tensorflow 1.3. At least for dummy_pose_estimation.py, but other parts of code I didn't test may be still incompatible.
