### ISSUE TITLE
where you download gain people video?

### ISSUE THREAD

**Issue by youarewe** [marian-margeta/gait-recognition#2]
Thank you for your code providing  me a  good idea to recognition gait. but, the walking video is Recorded by yourself?

**Comment by youarewe** [comment]
TUM GAID, I know that

**Comment by marian-margeta** [comment]
Yes. As you wrote, the TUM GAID DB was used - https://www.mmk.ei.tum.de/verschiedenes/tum-gaid-database/

**Comment by youarewe** [comment]
I hava sent the Agreement to tumgaid@mmk.ei.tum.de. but I didn't receive any reply.The agrement like that
![20180110201319](https://user-images.githubusercontent.com/22970855/34772482-fcefd8c2-f642-11e7-8d89-f7f4e0d1c878.png)
Could you show me where is the problem?

**Comment by marian-margeta** [comment]
Maybe you have bad email address. I sent it to tum_gaid@mmk.ei.tum.de

**Comment by youarewe** [comment]
Thank you. I will try it with my gmail again.
