### ISSUE TITLE
video frame is a image？

### ISSUE THREAD

**Issue by jackweiwang** [marian-margeta/gait-recognition#4]
Hi：
    I want run Gait recognition， I read README， but  i don‘t understand following code:

```py
# Create features from input frames in shape (TIME, HEIGHT, WIDTH, CHANNELS) 
spatial_features = net_pose.feed_forward_features(video_frames)
```

The video_frames is a Matrix or  other data?
How should I fill in it? opencv?

Thank you

**Comment by marian-margeta** [comment]
Hi,
it should be numpy tensor with shape (TIME, HEIGHT, WIDTH, CHANNELS) as states in comment. You can get it e.g. with opencv

**Comment by jackweiwang** [comment]
sorry，I didn't find it ，Can you Give me a link or document

**Comment by marian-margeta** [comment]
maybe smt. like this 
```python
cap = cv2.VideoCapture(video_path)
frames = []
while True:
  stat, frame = cap.read()

  if not stat:
    break

  frames .append(frame)

imgs = np.array(frames)
```

**Comment by jackweiwang** [comment]
# - - I know you're trying to help me， But  i don't know much about tensorflow. so The above problem cannot be solved. 
![image](https://user-images.githubusercontent.com/19305790/38653101-938eab88-3e3b-11e8-998d-44829b93656f.png)
I don't know what parameters it needs
