### ISSUE TITLE
how to center people?

### ISSUE THREAD

**Issue by jasonyuan97** [marian-margeta/gait-recognition#6]
Hi Marian,
I am trying to implement gait-recognition with your code, but, as you know, the images downloaded from TUMGAID database are raw frames, and I wonder if you have any code or suggestions on how to center people in the frames so that I can implement gait-recognition? 
Thanks in advance!

**Comment by marian-margeta** [comment]
Hi @jasonyuan97 
As the background in TUM GAID is quite immutable I used OpenCV's background subtraction method `cv2.createBackgroundSubtractorMOG2` to get binary silhouette of a pedestrian. Then, according to the shilouette's centroid, the frame is cropped so a pedestrian is approximately in the center of the image. It is done with some margin from top and bottom so the person fills about 4/5 to 3/5 of the picture's height. 

But in real-world scenario the more sophisticated method should be used, e.g. Kalman filter to track the motion + pedestrian detection based on HOG to make corrections in trajectory.

**Comment by arun121cs** [comment]
Have you tested this algorithm on any other dataset? Kindly update.
